// vue-完整项目/vue/my-vue/src/views/login.vue
<!--  -->
<template>
    <div>
       用户名:<input type="text" v-model="username"><br>
       密码：<input type='text' v-model="password"><br>
       <button @click="login">登录</button>
    </div>
</template>

<script>
//import request from '../util/request'
import {login} from '../api/index'

export default {
  data () {
    return {
        username:"",
        password:""
    };
  },
 methods: {
      login(){
        //接口登录
        if(this.username && this.password){
        //    request.post('/api/login',{username:this.username,password:this.password}).then((res) =>{
        //     //  console.log(res)
        //   //存到本地
        //  // console.log(res)
        //  if(res.data.code===1){
        //    alert("登录成功")
        //    localStorage.setItem('token',res.data.token)
        //    //跳页面
        //    this.$router.push('/List')
        //  }
        // })
        }
       login(this.username,this.password).then(res=>{
          if(res.data.code===1){
            alert("登录成功")
            localStorage.setItem("token",res.data.token)
            this.$router.push('/list')
          }
       })

      }
}
}
</script>

// vue-完整项目/旅游项目/cms-web/react/my-app/src/views/login.js
import React, { Component } from 'react'

export default class login extends Component {
    state={
        isShow:true
    }
    render() {
        const{isShow}=this.state
        return (
            <div>
                <input type="text" ref='username'/><br/>
                <input type="text" ref='password'/><br/>
                {
                    isShow?<div>
                        <button onClick={()=>this.submitFunc('/login')}>登录</button>
                        <p onClick={()=>this.setState({isShow:false})}>没有账号,去注册</p>
                    </div>:<div>
                        <button onClick={()=>this.submitFunc('/register')}>注册</button>
                        <p  onClick={()=>this.setState({isShow:true})}>已有帐号,去登录</p>
                    </div>
                }
                
            </div>
        )
    }
    submitFunc=async (url)=>{
        let submitData={
            username:this.refs.username.value,
            password:this.refs.password.value
        }
        if(submitData.username==='') return alert('帐号不能为空')
        if(submitData.password==='') return alert('密码不能为空')
        let res=await this.http('post',url,submitData)
        const{code,msg,data}=res.data
        alert(msg)
        if(code===0)
        {
            localStorage.setItem('token',data.token)
            this.props.history.push('/home')
        }
    }
}
